accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('signup', views.signup_view, name="signup"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "article"
urlpatterns = [
    path('', views.articlesList, name="list"),
    path('create', views.articleCreate, name="create"),
    path('<slug>', views.articlesDitail, name="detail"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import view
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from articles.views import articlesList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', view.about),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', articlesList),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Articles(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    body = models.TextField()
    time = models.DateField(auto_now_add=True)
    image = models.ImageField(default='defualt.jpg', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    # uploadat = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.slug

    def snipet(self):
        return '... ' + self.body[:50]

articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Articles
        fields = ['title', 'slug', 'body', 'image']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('article:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('article:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('article:list')

articles/views.py
from django.db.models.fields import DateField
from django.shortcuts import redirect, render, HttpResponse
from . import models
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.


def articlesList(request):
    articlces = models.Articles.objects.all().order_by('-time')

    args = {'articles': articlces}
    return render(request, 'articles/articlesList.html', args)


def articlesDitail(request, slug):
    textBody = models.Articles.objects.get(slug=slug)
    return render(request, 'articles/articleDetail.html', {'textBody': textBody})


@login_required(login_url="/accounts/login")
def articleCreate(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid:
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('article:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/articleCreate.html', {'form': form})

accounts/templates/accounts/login.html
{%extends 'base.html'%}

{%block title%}
log in
{%endblock%}

{%block body%}
<form action="{%url 'accounts:login' %}" class="site-form" method="post">
    {{form}}
    {%csrf_token%}
    {%if request.GET.next%}
    <input type="hidden" , name="next" , value="{{request.GET.next}}">
    {%endif%}
    <input type="submit" value="login">
</form>
{%endblock%}

accounts/templates/accounts/signup.html
{%extends 'base.html'%}

{%block title%}
Sign Up
{%endblock%}

{%block body%}
<form action="{%url 'accounts:signup' %}" class="site-form" method="post">
    {{form}}
    {%csrf_token%}
    <input type="submit" value="sign up">
</form>
{%endblock%}

articles/templates/articles/articleCreate.html
{%extends 'base.html'%}
{%load static%}
{%block title%}
create article
{%endblock%}
{%block body%}
<div class="create-article">
    <p>it is create page</p>
    <form action="{%url 'article:create'%}" method="post" class="site-form" enctype="multipart/form-data">
        {{form}}
        {%csrf_token%}
        <input type="submit" value="create">
    </form>
</div>
<script src="{%static 'slugify.js'%}"></script>
{%endblock%}

articles/templates/articles/articleDetail.html
{%extends 'base.html'%}
{%load static%}

{%block title%}
{{textBody.title}}
{%endblock%}

{%block link%}
<link rel="stylesheet" href="{%static 'styleDetail.css'%}">
{%endblock%}

{%block body%}
<div class="articleDetail">
    <div class="article">
        <img src="{{textBody.image.url}}" alt="">
        <h2>{{textBody.title}}</h2>
        <p>{{textBody.body}}</p>
        <h4>{{textBody.author}</h4>
        <h5>{{textBody.time}}</h5>
    </div>
</div>
{%endblock%}

articles/templates/articles/articlesList.html
{% extends 'base.html'%}
{%load static%}

{% block title%}
articles
{%endblock%}

{%block link%}
<link rel="stylesheet" href="{%static 'styles.css'%}">
{%endblock%}

{%block body%}

<p>Article List</p>
<div class="articles">
    {%for counter in articles %}
    <div class="article">
        <a href="{%url 'article:detail' slug=counter.slug %}">{{counter.title}}</a>
        <h3>{{counter.snipet}}</h3>
        <h5>{{counter.time}}</h5>
        <p class="author">written by {{counter.author}}</p>
    </div>
    {%endfor%}
</div>

{%endblock%}

templates/about.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <p>سلام <br> ای صفحه ی ذرباره ی ما است</p>
</body>

</html>

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%block link%}
    <link rel="stylesheet" href="{%static 'styles.css'%}">
    {%endblock%}
    <title>
        {%block title%}
        x
        {%endblock%}
    </title>
</head>

<body>

    </div>
    <header>
        <nav>
            <ul>
                {%if user.is_authenticated%}
                <li>
                    <form class="logout-list" action="{%url 'accounts:logout' %}" method="post">
                        {%csrf_token%}
                        <button type="submit">log out</button>
                    </form>
                </li>
                <li>
                    <a class="highlight" href="{%url 'article:create'%}">create new article</a>
                </li>
                {%else%}
                <li>
                    <a href="{%url 'accounts:login'%}">login</a>
                </li>
                <li>
                    <a href="{%url 'accounts:signup'%}">sign up</a>
                </li>
                {%endif%}
            </ul>
        </nav>
    </header>
    <div class="wrapper">
        {%block body%}

        {%endblock%}
</body>

</html>

templates/home.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <p>سلام <br> این صفحه ی اصلی ما است </p>
</body>

</html>